# Not source: generated token tables for tools/gdc_decompile.py.
# Regenerate from a gdsdecomp checkout when Godot bumps the bytecode version;
# see that script's docstring for which files these come from.
LOCAL_TOKENS = [
    'TK_EMPTY',
    'TK_ANNOTATION',
    'TK_IDENTIFIER',
    'TK_CONSTANT',
    'TK_OP_LESS',
    'TK_OP_LESS_EQUAL',
    'TK_OP_GREATER',
    'TK_OP_GREATER_EQUAL',
    'TK_OP_EQUAL',
    'TK_OP_NOT_EQUAL',
    'TK_OP_AND',
    'TK_OP_OR',
    'TK_OP_NOT',
    'TK_AMPERSAND_AMPERSAND',
    'TK_PIPE_PIPE',
    'TK_BANG',
    'TK_OP_BIT_AND',
    'TK_OP_BIT_OR',
    'TK_OP_BIT_INVERT',
    'TK_OP_BIT_XOR',
    'TK_OP_SHIFT_LEFT',
    'TK_OP_SHIFT_RIGHT',
    'TK_OP_ADD',
    'TK_OP_SUB',
    'TK_OP_MUL',
    'TK_STAR_STAR',
    'TK_OP_DIV',
    'TK_OP_MOD',
    'TK_OP_ASSIGN',
    'TK_OP_ASSIGN_ADD',
    'TK_OP_ASSIGN_SUB',
    'TK_OP_ASSIGN_MUL',
    'TK_STAR_STAR_EQUAL',
    'TK_OP_ASSIGN_DIV',
    'TK_OP_ASSIGN_MOD',
    'TK_OP_ASSIGN_SHIFT_LEFT',
    'TK_OP_ASSIGN_SHIFT_RIGHT',
    'TK_OP_ASSIGN_BIT_AND',
    'TK_OP_ASSIGN_BIT_OR',
    'TK_OP_ASSIGN_BIT_XOR',
    'TK_CF_IF',
    'TK_CF_ELIF',
    'TK_CF_ELSE',
    'TK_CF_FOR',
    'TK_CF_WHILE',
    'TK_CF_BREAK',
    'TK_CF_CONTINUE',
    'TK_CF_PASS',
    'TK_CF_RETURN',
    'TK_CF_MATCH',
    'TK_CF_WHEN',
    'TK_PR_AS',
    'TK_PR_ASSERT',
    'TK_PR_AWAIT',
    'TK_PR_BREAKPOINT',
    'TK_PR_CLASS',
    'TK_PR_CLASS_NAME',
    'TK_PR_CONST',
    'TK_PR_ENUM',
    'TK_PR_EXTENDS',
    'TK_PR_FUNCTION',
    'TK_OP_IN',
    'TK_PR_IS',
    'TK_PR_NAMESPACE',
    'TK_PR_PRELOAD',
    'TK_SELF',
    'TK_PR_SIGNAL',
    'TK_PR_STATIC',
    'TK_PR_SUPER',
    'TK_PR_TRAIT',
    'TK_PR_VAR',
    'TK_PR_VOID',
    'TK_PR_YIELD',
    'TK_BRACKET_OPEN',
    'TK_BRACKET_CLOSE',
    'TK_CURLY_BRACKET_OPEN',
    'TK_CURLY_BRACKET_CLOSE',
    'TK_PARENTHESIS_OPEN',
    'TK_PARENTHESIS_CLOSE',
    'TK_COMMA',
    'TK_SEMICOLON',
    'TK_PERIOD',
    'TK_PERIOD_PERIOD',
    'TK_PERIOD_PERIOD_PERIOD',
    'TK_COLON',
    'TK_DOLLAR',
    'TK_FORWARD_ARROW',
    'TK_UNDERSCORE',
    'TK_NEWLINE',
    'TK_INDENT',
    'TK_DEDENT',
    'TK_CONST_PI',
    'TK_CONST_TAU',
    'TK_CONST_INF',
    'TK_CONST_NAN',
    'TK_VCS_CONFLICT_MARKER',
    'TK_BACKTICK',
    'TK_QUESTION_MARK',
    'TK_ERROR',
    'TK_EOF',
    'TK_MAX',
]
LOCAL_TO_GLOBAL = {
    'TK_EMPTY': 'G_TK_EMPTY',
    'TK_ANNOTATION': 'G_TK_ANNOTATION',
    'TK_IDENTIFIER': 'G_TK_IDENTIFIER',
    'TK_CONSTANT': 'G_TK_CONSTANT',
    'TK_OP_LESS': 'G_TK_OP_LESS',
    'TK_OP_LESS_EQUAL': 'G_TK_OP_LESS_EQUAL',
    'TK_OP_GREATER': 'G_TK_OP_GREATER',
    'TK_OP_GREATER_EQUAL': 'G_TK_OP_GREATER_EQUAL',
    'TK_OP_EQUAL': 'G_TK_OP_EQUAL',
    'TK_OP_NOT_EQUAL': 'G_TK_OP_NOT_EQUAL',
    'TK_OP_AND': 'G_TK_OP_AND',
    'TK_OP_OR': 'G_TK_OP_OR',
    'TK_OP_NOT': 'G_TK_OP_NOT',
    'TK_AMPERSAND_AMPERSAND': 'G_TK_AMPERSAND_AMPERSAND',
    'TK_PIPE_PIPE': 'G_TK_PIPE_PIPE',
    'TK_BANG': 'G_TK_BANG',
    'TK_OP_BIT_AND': 'G_TK_OP_BIT_AND',
    'TK_OP_BIT_OR': 'G_TK_OP_BIT_OR',
    'TK_OP_BIT_INVERT': 'G_TK_OP_BIT_INVERT',
    'TK_OP_BIT_XOR': 'G_TK_OP_BIT_XOR',
    'TK_OP_SHIFT_LEFT': 'G_TK_OP_SHIFT_LEFT',
    'TK_OP_SHIFT_RIGHT': 'G_TK_OP_SHIFT_RIGHT',
    'TK_OP_ADD': 'G_TK_OP_ADD',
    'TK_OP_SUB': 'G_TK_OP_SUB',
    'TK_OP_MUL': 'G_TK_OP_MUL',
    'TK_STAR_STAR': 'G_TK_STAR_STAR',
    'TK_OP_DIV': 'G_TK_OP_DIV',
    'TK_OP_MOD': 'G_TK_OP_MOD',
    'TK_OP_ASSIGN': 'G_TK_OP_ASSIGN',
    'TK_OP_ASSIGN_ADD': 'G_TK_OP_ASSIGN_ADD',
    'TK_OP_ASSIGN_SUB': 'G_TK_OP_ASSIGN_SUB',
    'TK_OP_ASSIGN_MUL': 'G_TK_OP_ASSIGN_MUL',
    'TK_STAR_STAR_EQUAL': 'G_TK_STAR_STAR_EQUAL',
    'TK_OP_ASSIGN_DIV': 'G_TK_OP_ASSIGN_DIV',
    'TK_OP_ASSIGN_MOD': 'G_TK_OP_ASSIGN_MOD',
    'TK_OP_ASSIGN_SHIFT_LEFT': 'G_TK_OP_ASSIGN_SHIFT_LEFT',
    'TK_OP_ASSIGN_SHIFT_RIGHT': 'G_TK_OP_ASSIGN_SHIFT_RIGHT',
    'TK_OP_ASSIGN_BIT_AND': 'G_TK_OP_ASSIGN_BIT_AND',
    'TK_OP_ASSIGN_BIT_OR': 'G_TK_OP_ASSIGN_BIT_OR',
    'TK_OP_ASSIGN_BIT_XOR': 'G_TK_OP_ASSIGN_BIT_XOR',
    'TK_CF_IF': 'G_TK_CF_IF',
    'TK_CF_ELIF': 'G_TK_CF_ELIF',
    'TK_CF_ELSE': 'G_TK_CF_ELSE',
    'TK_CF_FOR': 'G_TK_CF_FOR',
    'TK_CF_WHILE': 'G_TK_CF_WHILE',
    'TK_CF_BREAK': 'G_TK_CF_BREAK',
    'TK_CF_CONTINUE': 'G_TK_CF_CONTINUE',
    'TK_CF_PASS': 'G_TK_CF_PASS',
    'TK_CF_RETURN': 'G_TK_CF_RETURN',
    'TK_CF_MATCH': 'G_TK_CF_MATCH',
    'TK_CF_WHEN': 'G_TK_CF_WHEN',
    'TK_PR_AS': 'G_TK_PR_AS',
    'TK_PR_ASSERT': 'G_TK_PR_ASSERT',
    'TK_PR_AWAIT': 'G_TK_PR_AWAIT',
    'TK_PR_BREAKPOINT': 'G_TK_PR_BREAKPOINT',
    'TK_PR_CLASS': 'G_TK_PR_CLASS',
    'TK_PR_CLASS_NAME': 'G_TK_PR_CLASS_NAME',
    'TK_PR_CONST': 'G_TK_PR_CONST',
    'TK_PR_ENUM': 'G_TK_PR_ENUM',
    'TK_PR_EXTENDS': 'G_TK_PR_EXTENDS',
    'TK_PR_FUNCTION': 'G_TK_PR_FUNCTION',
    'TK_OP_IN': 'G_TK_OP_IN',
    'TK_PR_IS': 'G_TK_PR_IS',
    'TK_PR_NAMESPACE': 'G_TK_PR_NAMESPACE',
    'TK_PR_PRELOAD': 'G_TK_PR_PRELOAD',
    'TK_SELF': 'G_TK_SELF',
    'TK_PR_SIGNAL': 'G_TK_PR_SIGNAL',
    'TK_PR_STATIC': 'G_TK_PR_STATIC',
    'TK_PR_SUPER': 'G_TK_PR_SUPER',
    'TK_PR_TRAIT': 'G_TK_PR_TRAIT',
    'TK_PR_VAR': 'G_TK_PR_VAR',
    'TK_PR_VOID': 'G_TK_PR_VOID',
    'TK_PR_YIELD': 'G_TK_PR_YIELD',
    'TK_BRACKET_OPEN': 'G_TK_BRACKET_OPEN',
    'TK_BRACKET_CLOSE': 'G_TK_BRACKET_CLOSE',
    'TK_CURLY_BRACKET_OPEN': 'G_TK_CURLY_BRACKET_OPEN',
    'TK_CURLY_BRACKET_CLOSE': 'G_TK_CURLY_BRACKET_CLOSE',
    'TK_PARENTHESIS_OPEN': 'G_TK_PARENTHESIS_OPEN',
    'TK_PARENTHESIS_CLOSE': 'G_TK_PARENTHESIS_CLOSE',
    'TK_COMMA': 'G_TK_COMMA',
    'TK_SEMICOLON': 'G_TK_SEMICOLON',
    'TK_PERIOD': 'G_TK_PERIOD',
    'TK_PERIOD_PERIOD': 'G_TK_PERIOD_PERIOD',
    'TK_PERIOD_PERIOD_PERIOD': 'G_TK_PERIOD_PERIOD_PERIOD',
    'TK_COLON': 'G_TK_COLON',
    'TK_DOLLAR': 'G_TK_DOLLAR',
    'TK_FORWARD_ARROW': 'G_TK_FORWARD_ARROW',
    'TK_UNDERSCORE': 'G_TK_UNDERSCORE',
    'TK_NEWLINE': 'G_TK_NEWLINE',
    'TK_INDENT': 'G_TK_INDENT',
    'TK_DEDENT': 'G_TK_DEDENT',
    'TK_CONST_PI': 'G_TK_CONST_PI',
    'TK_CONST_TAU': 'G_TK_CONST_TAU',
    'TK_CONST_INF': 'G_TK_CONST_INF',
    'TK_CONST_NAN': 'G_TK_CONST_NAN',
    'TK_VCS_CONFLICT_MARKER': 'G_TK_VCS_CONFLICT_MARKER',
    'TK_BACKTICK': 'G_TK_BACKTICK',
    'TK_QUESTION_MARK': 'G_TK_QUESTION_MARK',
    'TK_ERROR': 'G_TK_ERROR',
    'TK_EOF': 'G_TK_EOF',
    'TK_MAX': 'G_TK_MAX',
}
TOKEN_TEXT = {
    'G_TK_ABSTRACT': 'abstract ',
    'G_TK_AMPERSAND_AMPERSAND': '&& ',
    'G_TK_BACKTICK': '`',
    'G_TK_BANG': '!',
    'G_TK_BRACKET_CLOSE': ']',
    'G_TK_BRACKET_OPEN': '[',
    'G_TK_CF_BREAK': 'break',
    'G_TK_CF_CASE': 'case ',
    'G_TK_CF_CONTINUE': 'continue',
    'G_TK_CF_DO': 'do ',
    'G_TK_CF_ELIF': 'elif ',
    'G_TK_CF_ELSE': 'else',
    'G_TK_CF_FOR': 'for ',
    'G_TK_CF_IF': 'if ',
    'G_TK_CF_MATCH': 'match',
    'G_TK_CF_PASS': 'pass',
    'G_TK_CF_RETURN': 'return',
    'G_TK_CF_SWITCH': 'switch ',
    'G_TK_CF_WHEN': 'when ',
    'G_TK_CF_WHILE': 'while ',
    'G_TK_COLON': ':',
    'G_TK_COMMA': ', ',
    'G_TK_CONSTANT': '\\"\\"\\"',
    'G_TK_CONST_INF': 'INF',
    'G_TK_CONST_NAN': 'NAN',
    'G_TK_CONST_PI': 'PI',
    'G_TK_CONST_TAU': 'TAU',
    'G_TK_CURLY_BRACKET_CLOSE': '}',
    'G_TK_CURLY_BRACKET_OPEN': '{',
    'G_TK_DOLLAR': '$',
    'G_TK_FORWARD_ARROW': '->',
    'G_TK_OP_ADD': '+ ',
    'G_TK_OP_AND': 'and ',
    'G_TK_OP_ASSIGN': '= ',
    'G_TK_OP_ASSIGN_ADD': '+= ',
    'G_TK_OP_ASSIGN_BIT_AND': '&= ',
    'G_TK_OP_ASSIGN_BIT_OR': '|= ',
    'G_TK_OP_ASSIGN_BIT_XOR': '^= ',
    'G_TK_OP_ASSIGN_DIV': '/= ',
    'G_TK_OP_ASSIGN_MOD': '%= ',
    'G_TK_OP_ASSIGN_MUL': '*= ',
    'G_TK_OP_ASSIGN_SHIFT_LEFT': '<<= ',
    'G_TK_OP_ASSIGN_SHIFT_RIGHT': '>>= ',
    'G_TK_OP_ASSIGN_SUB': '-= ',
    'G_TK_OP_BIT_AND': '& ',
    'G_TK_OP_BIT_INVERT': '~ ',
    'G_TK_OP_BIT_OR': '| ',
    'G_TK_OP_BIT_XOR': '^ ',
    'G_TK_OP_DIV': '/ ',
    'G_TK_OP_EQUAL': '== ',
    'G_TK_OP_GREATER': '> ',
    'G_TK_OP_GREATER_EQUAL': '>= ',
    'G_TK_OP_IN': 'in ',
    'G_TK_OP_LESS': '< ',
    'G_TK_OP_LESS_EQUAL': '<= ',
    'G_TK_OP_MINUS_MINUS': '--',
    'G_TK_OP_MOD': '%',
    'G_TK_OP_MUL': '* ',
    'G_TK_OP_NOT': 'not ',
    'G_TK_OP_NOT_EQUAL': '!= ',
    'G_TK_OP_OR': 'or ',
    'G_TK_OP_PLUS_PLUS': '++',
    'G_TK_OP_SHIFT_LEFT': '<< ',
    'G_TK_OP_SHIFT_RIGHT': '>> ',
    'G_TK_OP_SUB': '- ',
    'G_TK_PARENTHESIS_CLOSE': ')',
    'G_TK_PARENTHESIS_OPEN': '(',
    'G_TK_PERIOD': '.',
    'G_TK_PERIOD_PERIOD': '..',
    'G_TK_PERIOD_PERIOD_PERIOD': '...',
    'G_TK_PIPE_PIPE': '|| ',
    'G_TK_PR_AS': 'as ',
    'G_TK_PR_ASSERT': 'assert ',
    'G_TK_PR_AWAIT': 'await ',
    'G_TK_PR_BREAKPOINT': 'breakpoint',
    'G_TK_PR_CLASS': 'class ',
    'G_TK_PR_CLASS_NAME': 'class_name ',
    'G_TK_PR_CONST': 'const ',
    'G_TK_PR_ENUM': 'enum ',
    'G_TK_PR_EXPORT': 'export ',
    'G_TK_PR_EXTENDS': 'extends ',
    'G_TK_PR_FUNCTION': 'func',
    'G_TK_PR_IS': 'is ',
    'G_TK_PR_MASTER': 'master ',
    'G_TK_PR_MASTERSYNC': 'mastersync ',
    'G_TK_PR_NAMESPACE': 'namespace ',
    'G_TK_PR_ONREADY': 'onready ',
    'G_TK_PR_PRELOAD': 'preload',
    'G_TK_PR_PUPPET': 'puppet ',
    'G_TK_PR_PUPPETSYNC': 'puppetsync ',
    'G_TK_PR_REMOTE': 'remote ',
    'G_TK_PR_REMOTESYNC': 'remotesync ',
    'G_TK_PR_SETGET': ' setget ',
    'G_TK_PR_SIGNAL': 'signal ',
    'G_TK_PR_SLAVE': 'slave ',
    'G_TK_PR_SLAVESYNC': 'slavesync ',
    'G_TK_PR_STATIC': 'static ',
    'G_TK_PR_SUPER': 'super',
    'G_TK_PR_SYNC': 'sync ',
    'G_TK_PR_TOOL': 'tool',
    'G_TK_PR_TRAIT': 'trait ',
    'G_TK_PR_VAR': 'var ',
    'G_TK_PR_VOID': 'void ',
    'G_TK_PR_YIELD': 'yield',
    'G_TK_QUESTION_MARK': '?',
    'G_TK_SELF': 'self',
    'G_TK_SEMICOLON': ';',
    'G_TK_STAR_STAR': '** ',
    'G_TK_STAR_STAR_EQUAL': '**= ',
    'G_TK_UNDERSCORE': '_',
    'G_TK_WILDCARD': '_',
}
